//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPapp.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SOAPapp.ServiceReference1.HelloWorldResponse HelloWorld(SOAPapp.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPapp.ServiceReference1.HelloWorldResponse> HelloWorldAsync(SOAPapp.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Farenheit2Celsius", ReplyAction="*")]
        float Farenheit2Celsius(float temp_f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Farenheit2Celsius", ReplyAction="*")]
        System.Threading.Tasks.Task<float> Farenheit2CelsiusAsync(float temp_f);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Celsius2Farenheit", ReplyAction="*")]
        float Celsius2Farenheit(float temp_c);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Celsius2Farenheit", ReplyAction="*")]
        System.Threading.Tasks.Task<float> Celsius2FarenheitAsync(float temp_c);
        
        // CODEGEN: Generating message contract since element name file_name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadJSON", ReplyAction="*")]
        SOAPapp.ServiceReference1.LoadJSONResponse LoadJSON(SOAPapp.ServiceReference1.LoadJSONRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadJSON", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPapp.ServiceReference1.LoadJSONResponse> LoadJSONAsync(SOAPapp.ServiceReference1.LoadJSONRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SOAPapp.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SOAPapp.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPapp.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SOAPapp.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadJSONRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadJSON", Namespace="http://tempuri.org/", Order=0)]
        public SOAPapp.ServiceReference1.LoadJSONRequestBody Body;
        
        public LoadJSONRequest() {
        }
        
        public LoadJSONRequest(SOAPapp.ServiceReference1.LoadJSONRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadJSONRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string file_name;
        
        public LoadJSONRequestBody() {
        }
        
        public LoadJSONRequestBody(string file_name) {
            this.file_name = file_name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadJSONResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadJSONResponse", Namespace="http://tempuri.org/", Order=0)]
        public SOAPapp.ServiceReference1.LoadJSONResponseBody Body;
        
        public LoadJSONResponse() {
        }
        
        public LoadJSONResponse(SOAPapp.ServiceReference1.LoadJSONResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadJSONResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoadJSONResult;
        
        public LoadJSONResponseBody() {
        }
        
        public LoadJSONResponseBody(string LoadJSONResult) {
            this.LoadJSONResult = LoadJSONResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : SOAPapp.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<SOAPapp.ServiceReference1.WebServiceSoap>, SOAPapp.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPapp.ServiceReference1.HelloWorldResponse SOAPapp.ServiceReference1.WebServiceSoap.HelloWorld(SOAPapp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SOAPapp.ServiceReference1.HelloWorldRequest inValue = new SOAPapp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SOAPapp.ServiceReference1.HelloWorldRequestBody();
            SOAPapp.ServiceReference1.HelloWorldResponse retVal = ((SOAPapp.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPapp.ServiceReference1.HelloWorldResponse> SOAPapp.ServiceReference1.WebServiceSoap.HelloWorldAsync(SOAPapp.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPapp.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            SOAPapp.ServiceReference1.HelloWorldRequest inValue = new SOAPapp.ServiceReference1.HelloWorldRequest();
            inValue.Body = new SOAPapp.ServiceReference1.HelloWorldRequestBody();
            return ((SOAPapp.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        public int Add(int a, int b) {
            return base.Channel.Add(a, b);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int a, int b) {
            return base.Channel.AddAsync(a, b);
        }
        
        public float Farenheit2Celsius(float temp_f) {
            return base.Channel.Farenheit2Celsius(temp_f);
        }
        
        public System.Threading.Tasks.Task<float> Farenheit2CelsiusAsync(float temp_f) {
            return base.Channel.Farenheit2CelsiusAsync(temp_f);
        }
        
        public float Celsius2Farenheit(float temp_c) {
            return base.Channel.Celsius2Farenheit(temp_c);
        }
        
        public System.Threading.Tasks.Task<float> Celsius2FarenheitAsync(float temp_c) {
            return base.Channel.Celsius2FarenheitAsync(temp_c);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPapp.ServiceReference1.LoadJSONResponse SOAPapp.ServiceReference1.WebServiceSoap.LoadJSON(SOAPapp.ServiceReference1.LoadJSONRequest request) {
            return base.Channel.LoadJSON(request);
        }
        
        public string LoadJSON(string file_name) {
            SOAPapp.ServiceReference1.LoadJSONRequest inValue = new SOAPapp.ServiceReference1.LoadJSONRequest();
            inValue.Body = new SOAPapp.ServiceReference1.LoadJSONRequestBody();
            inValue.Body.file_name = file_name;
            SOAPapp.ServiceReference1.LoadJSONResponse retVal = ((SOAPapp.ServiceReference1.WebServiceSoap)(this)).LoadJSON(inValue);
            return retVal.Body.LoadJSONResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPapp.ServiceReference1.LoadJSONResponse> SOAPapp.ServiceReference1.WebServiceSoap.LoadJSONAsync(SOAPapp.ServiceReference1.LoadJSONRequest request) {
            return base.Channel.LoadJSONAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPapp.ServiceReference1.LoadJSONResponse> LoadJSONAsync(string file_name) {
            SOAPapp.ServiceReference1.LoadJSONRequest inValue = new SOAPapp.ServiceReference1.LoadJSONRequest();
            inValue.Body = new SOAPapp.ServiceReference1.LoadJSONRequestBody();
            inValue.Body.file_name = file_name;
            return ((SOAPapp.ServiceReference1.WebServiceSoap)(this)).LoadJSONAsync(inValue);
        }
    }
}
